### ISSUE TITLE
WSDL -  missing soap:binding element

### ISSUE THREAD

**Issue by Whivel** [wasabii/Cogito.AspNetCore.ServiceModel#2]
Hi,

I just saw an issue in then wsdl generation with Soap11 message version. 
The soap:binding element is missing inside the wsdl:binding element.

This element is necessary to identify the type of transport. WcfTestClient and SoapUI don't work without them.

**Comment by wasabii** [comment]
Yeah. Good catch. Was never using the TestClient, so never noticed it.

I also noticed apparently it's coming back with SOAP1.2 nomatter what you do, too. It's been about a year since I worked on this, so my memory is now fuzzy. But, I remember spending a lot of time jacking around with bindings to get it to emit the right stuff. Will take me a bit to get into it and refresh my WCF memory.

**Comment by wasabii** [comment]
Problem solved. Pushing new release in a second.

**Comment by wasabii** [comment]
New release pushed.

https://www.nuget.org/packages/Cogito.AspNetCore.ServiceModel/1.1.28

Thanks!
